from tkinter import *
window=Tk()
window.title("Login apppp")
window.geometry("400x400")
frame=Frame(master=window,height=200,width=360,bg="#d0efff")
name=Label(frame,text="Full Name ",bg="#3895D3",fg="white",width=12)
email=Label(frame,text="Email ID",bg="#3895D3",fg="white",width=12)
password=Label(frame,text="Enter Password",bg="#3895D3",fg="white",width=12)
name_entry=Entry(frame)
email_entry=Entry(frame)
password_entry=Entry(frame,show="*")
def display():
    name1=name_entry.get()
    greet="HEYYYY "+name1
    message="\nCONGRATULATIONS FOR YR NW ACNT"
    textbox.insert(END,greet)
    textbox.insert(END,message)
textbox=Text(bg="#BEBEBE",fg="black")
btn=Button(text="Create Account",command=display,bg="red")
frame.place(x=20,y=0)
name.place(x=20,y=20)
name_entry.place(x=150,y=20)
email.place(x=20,y=80)
email_entry.place(x=150,y=80)
password.place(x=20,y=140)
password_entry.place(x=150,y=140)
btn.place(x=130,y=210)
textbox.place(y=250)
window.mainloop()